In [28]:
import numpy as np
import pandas as pd

# **ZADANIE 1**

In [29]:
# ZADANIE 1

data = pd.read_csv('president_heights.csv')
heights = np.array(data['height(cm)']) 
print(heights) 
print()

# Średni wzrost
print("Mean height:         ", np.mean(heights))

# Odchylenie standardowe
print("Standard deviation:  ", np.std(heights))

# Najwyższy
print("Maximum height:      ", np.amax(heights))

# Najniższy
print("Minimum height:      ", np.amin(heights))

# 25 kwantyl
print("25th percentile:     ", np.percentile(heights, 25))

# Mediana
print("Median:              ", np.median(heights))

# 75 kwantyl
print("75th percentile:     ", np.percentile(heights, 75))

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]

Mean height:          179.73809523809524
Standard deviation:   6.931843442745892
Maximum height:       193
Minimum height:       163
25th percentile:      174.25
Median:               182.0
75th percentile:      183.0


# **ZADANIE 2**

In [30]:
# ZADANIE 2

from numpy import linalg
data2 = np.genfromtxt('Zadanie_2.csv', delimiter=';')
print(data2)

[[  1.   2.  15. -59.   9.   3.  75.   6.   7.   1.]
 [  0.   5.   0.   4.   6.  16.  44.   7.   1.   1.]
 [  7.  14.   3. -10.   9.  15.  73.   8.   2.   9.]
 [  1.   5.  15. -54.   5.  15.  35.   8.   6.   4.]
 [  0.   8.   5. -18.   7.  16.  91.   6.   7.   9.]
 [  7.  18.  23. -90.   4.   8.  31.   0.   1.   7.]
 [  2.   8.  20. -72.   4.   1.  91.   9.   4.   4.]
 [  4.  12.  18. -65.   6.   9.  76.   4.   9.   9.]
 [  7.  15.  13. -52.   5.   7.  54.   2.   7.   0.]
 [  2.   9.  15. -56.   6.   1.  98.   4.   8.   4.]]


In [31]:
eigenvectors = np.linalg.eig(data2)
print("Wektory własne: \n", eigenvectors)
print()
eigenvalues = linalg.eigvals(data2)
print("Wartości własne: \n", eigenvalues)

Wektory własne: 
 (array([104.34960192 +0.j        , -23.35660516+18.84992811j,
       -23.35660516-18.84992811j,  15.92989017 +0.j        ,
        -4.99456452 +0.j        ,   0.35205717 +5.80125175j,
         0.35205717 -5.80125175j,  -1.03383491 +0.j        ,
         3.87900166 +1.42651533j,   3.87900166 -1.42651533j]), array([[-0.29000475+0.j        , -0.07545445+0.07743149j,
        -0.07545445-0.07743149j, -0.03544485+0.j        ,
         0.42681634+0.j        , -0.22172831-0.29869259j,
        -0.22172831+0.29869259j,  0.41343726+0.j        ,
        -0.28670255+0.21891569j, -0.28670255-0.21891569j],
       [-0.24163153+0.j        ,  0.41229621+0.09197324j,
         0.41229621-0.09197324j,  0.45873475+0.j        ,
        -0.27056206+0.j        , -0.01331344+0.1422557j ,
        -0.01331344-0.1422557j , -0.31591047+0.j        ,
         0.41954481-0.10561864j,  0.41954481+0.10561864j],
       [-0.41060573+0.j        ,  0.37509638-0.00960818j,
         0.37509638+0.00960818j,  

In [32]:
import numpy as np
inverse = np.linalg.inv(data2)
print("Macierz odwrotna: \n", inverse)

Macierz odwrotna: 
 [[ 0.47461371  0.13269253 -0.24726695 -0.82965177  0.28250384 -0.17012825
   0.58274426  0.83686705  0.4146721  -1.56942847]
 [-0.38032531 -0.11226789  0.23216372  0.58853747 -0.2508954   0.10174485
  -0.40729564 -0.58325689 -0.2335154   1.11832726]
 [ 0.13559662  0.58950334 -0.24709855 -0.58789838 -0.30170699 -0.12721938
   0.23740295  1.01003036 -0.02151387 -0.64590149]
 [ 0.01425207  0.14570726 -0.04557569 -0.12721972 -0.08945184 -0.03756624
   0.03910376  0.23606066 -0.01436771 -0.11345749]
 [-0.09473246  0.01725249  0.19145597  0.32960274 -0.28626296  0.08348529
  -0.37577603 -0.27295934 -0.25855803  0.74691827]
 [ 0.16387032  0.10075684 -0.15404907 -0.29794662  0.16916877 -0.02827782
   0.20469921  0.28036265  0.15086178 -0.5882585 ]
 [ 0.04288003  0.02246462 -0.0366803  -0.09024915  0.04322146 -0.01047861
   0.06167348  0.07009721  0.0367806  -0.14185925]
 [-0.26858433 -0.21167346  0.25168367  0.55607234 -0.16804333  0.01066975
  -0.22435849 -0.52957038 -0.15

# **ZADANIE 3**

In [33]:
# ZADANIE 3

rainfall = pd.read_csv('Seattle2014.csv')['PRCP'].values
inches = rainfall / 254.0  # 1/10mm -> inches
inches.shape

(365,)

In [34]:
# Dni, kiedy nie padało
without_rain = np.count_nonzero(inches == 0)
print("Number days without rain:        ", without_rain)

# Dni, kiedy padało
with_rain = np.count_nonzero(inches)
print("Number days with rain:           ", with_rain)

# Dni, kiedy spadło powyżej 0,5" deszczu
above_05 = np.count_nonzero(inches > 0.5)
print("Days with more than 0.5 inches:  ", above_05)

# Dni, kiedy spadło poniżej 0,2" deszczu, ale padało
below_02 = np.count_nonzero((inches != 0) & (inches < 0.2))
print("Rainy days with < 0.2 inches:    ", below_02)

Number days without rain:         215
Number days with rain:            150
Days with more than 0.5 inches:   37
Rainy days with < 0.2 inches:     75


In [35]:
# Mediana opadów w deszczowe dni w 2014 roku
mask1 = np.ma.masked_equal(inches, 0)
print("Median precip on rainy days in 2014 (inches):    ", np.round(np.ma.median(mask1), 3))

# Mediana opadów latem w 2014 roku (czyli dni pomiędzy dniem 172 a 262)
mask2 = np.ma.masked_equal(inches[171:262], 0)
print("Median precip on summer days in 2014 (inches):   ", np.round(np.ma.median(mask2), 3))

# Maksymalne opady latem 2014 roku 
max_precip_summer = mask2.max()
# analogiczne do: np.max(inches[171:262])
print("Maximum precip on summer days in 2014 (inches):  ", np.round(max_precip_summer, 3))

# Maksymalne opady poza latem 2014 roku (czyli wiosna, jesień i zima)
spring_precip = inches[:171]
winter_autumn_precip = inches[263:]
precip_included = np.concatenate([spring_precip,winter_autumn_precip])
mask3 = np.ma.masked_equal(precip_included, 0)
max_precip_non_summer = mask3.max()
print("Median precip on non-summer rainy days (inches): ", np.round(max_precip_non_summer, 3))

Median precip on rainy days in 2014 (inches):     0.195
Median precip on summer days in 2014 (inches):    0.061
Maximum precip on summer days in 2014 (inches):   0.85
Median precip on non-summer rainy days (inches):  1.839


# **ZADANIE 4**

In [27]:
# ZADANIE 4

import math
A = [0,3,2,5]
B = [0,3,1,4]

# Dodaj A i B
A = np.array(A)
B = np.array(B)
print("A + B =", A + B)

# Odejmij B od A
print("A - B =", A - B)

# Pomnóż wektor A przez skalar a=4
a = 4
print("A * a =", A*a)

# Oblicz iloczyn skalarny wektorów A i B
print("Iloczyn skalarny =", np.dot(A, B))

# Znajdź długość wektora B
print("Długość wektora B =", np.linalg.norm(B))

A + B = [0 6 3 9]
A - B = [0 0 1 1]
A * a = [ 0 12  8 20]
Iloczyn skalarny = 31
Długość wektora B = 5.0990195135927845
